spring:
  application:
    name: userapi
  datasource:
    url: jdbc:mysql://localhost:3306/backend-user-api
    username: root
    password: Bajaj@2040
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: 9090

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

